name: TESTING - mtd to ibc integration

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      # checkout relayer
      - name: checkout relayer
        uses: actions/checkout@v2

      # build cache
      - uses: actions/cache@v1
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      # run tests
      - name: run mtd tests
        run: make test-mtd
