name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
      - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    steps:
    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go
    - name: Checkout Gaia
      uses: actions/checkout@master
      with:
        repository: cosmos/gaia
        ref: refs/heads/ibc-alpha
    - name: Install Gaia
      run: make install
    - name: Checkout relayer
      uses: actions/checkout@v2
    - name: Install Relayer
      run: make install
    - name: Run two-chains.sh demo
      run: |
        ./two-chains.sh
